export const SUBMIT_CATEGORIES_REQUESTED = 'SUBMIT_CATEGORIES_REQUESTED';
export const FETCH_CATEGORIES_REQUESTED = 'FETCH_CATEGORIES_REQUESTED';
export const FETCH_ONE_CATEGORIES_SUCCEEDED = 'FETCH_ONE_CATEGORIES_SUCCEEDED';
export const FETCH_CATEGORIES_SUCCEEDED = 'FETCH_CATEGORIES_SUCCEEDED';
export const DELETE_CATEGORIES_REQUESTED = 'DELETE_CATEGORIES_REQUESTED';
export const CLEAN_CATEGORIES_FORM = 'CLEAN_CATEGORIES_FORM';
