export const SUBMIT_PROJECTS_REQUESTED = 'SUBMIT_PROJECTS_REQUESTED';
export const FETCH_PROJECTS_REQUESTED = 'FETCH_PROJECTS_REQUESTED';
export const FETCH_ONE_PROJECTS_SUCCEEDED = 'FETCH_ONE_PROJECTS_SUCCEEDED';
export const FETCH_PROJECTS_SUCCEEDED = 'FETCH_PROJECTS_SUCCEEDED';
export const DELETE_PROJECTS_REQUESTED = 'DELETE_PROJECTS_REQUESTED';
export const CLEAN_PROJECTS_FORM = 'CLEAN_PROJECTS_FORM';
