export const SUBMIT_CONTACT_REQUESTED = 'SUBMIT_CONTACT_REQUESTED';
export const FETCH_CONTACT_REQUESTED = 'FETCH_CONTACT_REQUESTED';
export const FETCH_ONE_CONTACT_SUCCEEDED = 'FETCH_ONE_CONTACT_SUCCEEDED';
export const FETCH_CONTACT_SUCCEEDED = 'FETCH_CONTACT_SUCCEEDED';
export const DELETE_CONTACT_REQUESTED = 'DELETE_CONTACT_REQUESTED';
export const CLEAN_CONTACT_FORM = 'CLEAN_CONTACT_FORM';
export const SET_SYSTEM_MSG = 'SET_SYSTEM_MSG';
