export const SUBMIT_MEMBERS_REQUESTED = 'SUBMIT_MEMBERS_REQUESTED';
export const FETCH_MEMBERS_REQUESTED = 'FETCH_MEMBERS_REQUESTED';
export const FETCH_ONE_MEMBERS_SUCCEEDED = 'FETCH_ONE_MEMBERS_SUCCEEDED';
export const FETCH_MEMBERS_SUCCEEDED = 'FETCH_MEMBERS_SUCCEEDED';
export const DELETE_MEMBERS_REQUESTED = 'DELETE_MEMBERS_REQUESTED';
export const CLEAN_MEMBERS_FORM = 'CLEAN_MEMBERS_FORM';
