export const SUBMIT_SLIDE_REQUESTED = 'SUBMIT_SLIDE_REQUESTED';
export const FETCH_SLIDE_REQUESTED = 'FETCH_SLIDE_REQUESTED';
export const FETCH_ONE_SLIDE_SUCCEEDED = 'FETCH_ONE_SLIDE_SUCCEEDED';
export const FETCH_SLIDE_SUCCEEDED = 'FETCH_SLIDE_SUCCEEDED';
export const DELETE_SLIDE_REQUESTED = 'DELETE_SLIDE_REQUESTED';
export const CLEAN_SLIDE_FORM = 'CLEAN_SLIDE_FORM';
export const SET_SYSTEM_MSG = 'SET_SYSTEM_MSG';
