export const SUBMIT_LOGIN_REQUESTED = 'SUBMIT_LOGIN_REQUESTED';
export const CLEAN_LOGIN_FORM = 'CLEAN_LOGIN_FORM';
export const SET_SYSTEM_MSG = 'SET_SYSTEM_MSG';
export const SET_NEWS_LETTER = 'SET_NEWS_LETTER';
export const SET_NEWS_LETTER_REQUESTED = 'SET_NEWS_LETTER_REQUESTED';
export const CHECK_SUBSCRIPTION = 'CHECK_SUBSCRIPTION';
export const SET_REQUEST_FLAG = 'SET_REQUEST_FLAG';
