export const REQUIRED = 'Todos los campos requeridos';
export const GOBACK = 'Volver';
export const ADD = 'Agregar';
export const CANCEL = 'Cancelar';
export const SEND = 'Enviar';
export const TOYS_CAMPAIGN = 'Campaña Juguetes';
export const WRONG_PASSWORD = 'Las contraseñas no coinciden';
export const SHORT_PASSWORD = 'Las contraseñas no coinciden';
export const INVALID_PASSWORD = 'La contraseña debe contener al menos un número, una letra y un símbolo';
