const mainRoutes = {
  backOfficeRoutes: {
    home: '/backoffice/home',
    news: '/backoffice/news',
    newsForm: '/backoffice/news/create',
    activities: '/backoffice/activities',
    newActivity: '/backoffice/activities/create',
    categories: '/backoffice/categories',
    category: '/backoffice/category',
    testimonials: '/backoffice/testimonials',
    testimonialform: '/backoffice/testimonials/create',
    organization: '/backoffice/organization',
    slides: '/backoffice/slides',
    slideform: '/backoffice/slides/create',
    users: '/backoffice/user/create',
    members: '/backoffice/members',
    membersForm: '/backoffice/members/edit',
    organizationform: '/backoffice/organization/edit',
  },
  publicRoutes: {
    home: '/',
    organization: '/organizations',
    activity: '/activities',
    news: '/novedades',
    testimonial: '/testimonials',
    contact: '/contact',
    contribute: '/contribute',
    categories: '/categories',
    slides: '/slides',
    user: '/users',
    member: '/members',
    us: '/us',
    novelty: '/novelty',
    editProfile: '/editProfile',
    backOffice: '/backoffice',
    register: '/register',
    donate: '/donar',
    thanks: '/gracias',
  },
  landingPages: {
    toysCampaign: '/toys-campaign',
    schoolCampaign: '/school-campaign',
  },
};

export default {
  mainRoutes,
};
