const mainRoutes = {
  backOfficeRoutes: {
    home: '/',
    news: '/backoffice/news',
    newsForm: '/backoffice/news/create',
    activities: '/activity',
    newActivity: '/create-activity',
    categories: '/categories',
    category: '/category',
    testimonials: '/testimonials',
    testimonialform: '/create-testimonials',
    organization: '/organization',
    slides: '/slides',
    slideform: '/backoffice/create-slide',
    users: '/create-user',
    members: '/backoffice/members',
    membersForm: '/backoffice/members/edit',
    organizationform: '/organization/edit',
  },
  publicRoutes: {
    home: '/',
    organization: '/organizations',
    activity: '/activities',
    news: '/novedades',
    testimonial: '/testimonials',
    contact: '/contact',
    contribute: '/contribute',
    categories: '/categories',
    slides: '/slides',
    user: '/users',
    member: '/members',
    us: '/us',
    novelty: '/novelty',
    editProfile: '/editProfile',
    backOffice: '/backOffice',
    register: '/register',
    donate: '/donar',
    thanks: '/gracias',
  },
  landingPages: {
    toysCampaign: '/toys-campaign',
    schoolCampaign: '/school-campaign',
  },
};

export default {
  mainRoutes,
};
