export const SUBMIT_TESTIMONIAL_REQUESTED = 'SUBMIT_TESTIMONIAL_REQUESTED';
export const FETCH_TESTIMONIAL_REQUESTED = 'FETCH_TESTIMONIAL_REQUESTED';
export const FETCH_ONE_TESTIMONIAL_SUCCEEDED = 'FETCH_ONE_TESTIMONIAL_SUCCEEDED';
export const FETCH_TESTIMONIAL_SUCCEEDED = 'FETCH_TESTIMONIAL_SUCCEEDED';
export const DELETE_TESTIMONIAL_REQUESTED = 'DELETE_TESTIMONIAL_REQUESTED';
export const CLEAN_TESTIMONIAL_FORM = 'CLEAN_TESTIMONIAL_FORM';
export const SET_SYSTEM_MSG = 'SET_SYSTEM_MSG';
