export const FETCH_SLIDES_REQUESTED = 'FETCH_SLIDES_REQUESTED';
export const FETCH_SLIDES_SUCCEEDED = 'FETCH_SLIDES_SUCCEEDED';
export const FETCH_ORGANIZATION_REQUESTED = 'FETCH_ORGANIZATION_REQUESTED';
export const FETCH_ORGANIZATION_SUCCEEDED = 'FETCH_ORGANIZATION_SUCCEEDED';
