export const SUBMIT_ACTIVITIES_REQUESTED = 'SUBMIT_ACTIVITIES_REQUESTED';
export const FETCH_ACTIVITIES_REQUESTED = 'FETCH_ACTIVITIES_REQUESTED';
export const FETCH_ONE_ACTIVITIES_SUCCEEDED = 'FETCH_ONE_ACTIVITIES_SUCCEEDED';
export const FETCH_ACTIVITIES_SUCCEEDED = 'FETCH_ACTIVITIES_SUCCEEDED';
export const DELETE_ACTIVITIES_REQUESTED = 'DELETE_ACTIVITIES_REQUESTED';
export const CLEAN_ACTIVITIES_FORM = 'CLEAN_ACTIVITIES_FORM';
export const SET_SYSTEM_MSG = 'SET_SYSTEM_MSG';
